### ISSUE TITLE
Story thumbnails have varying height

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config#355] opened 2023-12-07 08:43 UTC
We do not enforce a common height on story thumbnails and the published content does not have consistent size / aspect ratio:

![image](https://github.com/NASA-IMPACT/veda-config/assets/3404817/f8db08c2-c2a6-49ae-8ea4-6a55ff8a7dfe)

1. Does our design intend these story cards to have the same size?
2. Should we fix them manually?
3. Or somehow crop them automatically, either during CI or on the page?

## Acceptance criteria

- [ ] If design intends same size, make existing thumbnails conform

**Comment by aboydnw** [comment] 2024-05-04 17:33
@j08lue This ticket doesn't seem needed anymore, based on the recent catalog redesign and what I see in the E&A interface. Am I seeing that correctly?

**Comment by j08lue** [comment] 2024-05-06 09:38
Good call. Let's see how EarthData Dashboard datasets and layers look in these improved interfaces: https://github.com/NASA-IMPACT/veda-config/pull/360

Varying thumbnail height is indeed not an issue in the new catalog: 
![image](https://github.com/NASA-IMPACT/veda-config/assets/3404817/3b4e72ef-16e5-4991-bbcc-e22cf7d152cc)

In the E&A layer overview it is
![image](https://github.com/NASA-IMPACT/veda-config/assets/3404817/3f0df3fb-bd59-48f4-b719-84fae02ef3ec)

However, we are planning on changing that layout to use the same layout as the catalog.

- https://github.com/NASA-IMPACT/veda-ui/issues/932

So this issue will become obsolete soon. An interim fix would still be welcome - should be a quick fix with ImageMagick or so, perhaps also converting the images to webp in the process...

**Comment by dzole0311** [comment] 2024-06-10 09:09
Closing this since with the new Catalog view now ported to the Dataset Selector modal in E&A in [973](https://github.com/NASA-IMPACT/veda-ui/issues/973), the issue is obsolete.

**Closed by dzole0311** 2024-06-10 09:09 UTC
Labels: good first issue
